sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t test/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true test/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react-app
  env: Docker-react-app-env-1
  bucket_name: elasticbeanstalk-us-east-1-593243147186
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY